# RFM Feature Engineering

This notebook computes Recency, Frequency, and Monetary (RFM) metrics from the cleaned retail dataset.
Feature engineering is performed in both SQL (canonical) and Pandas (validation), with quantile-scored RFM features saved for segmentation modeling.

---

RFM Metric Definitions:
- **Recency** – Days since the customer's last purchase (lower is better)
- **Frequency** – Total number of unique invoices per customer
- **Monetary** – Total revenue generated per customer (quantity × price)
- **R / F / M Scores** – Quartile-based scores (1–4) assigned via NTILE in SQL or `qcut`/`rank` in Pandas
- **RFM Score** – Composite score combining individual R, F, and M scores

In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, text

# Local src

from src.utils.eda_utils import df_overview
from src.tasks.pd_feature_engineering import pd_feature_engineering
from src.pipelines.pipeline import feature_engineering_pipeline

from src.config.config import DB_CREATED
from src.config.paths import PROCESSED_DIR

print('Done')

Done

In [2]:
# the SQL version of feature engineering in this project.

feature_engineering_pipeline()

engine = create_engine(DB_CREATED)

df_sql_featured = pd.read_sql(text("SELECT * FROM mart.mart_customer_rfm_features"), engine)
print(f"df_rfm loaded: {df_sql_featured.shape[0]} rows, {df_sql_featured.shape[1]} columns")
df_sql_featured.set_index('customer_id', inplace=True)
df_sql_featured.sort_index(inplace=True)
df_sql_featured

2026-04-26 14:16:14 | INFO    | prefect | Starting temporary server on http://127.0.0.1:8508
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/health "HTTP/1.1 200 OK"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/admin/version "HTTP/1.1 200 OK"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/csrf-token?client=1a860c65-9704-4922-b493-668f6e9e864d "HTTP/1.1 422 Unprocessable Entity"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/flows/ "HTTP/1.1 200 OK"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/flow_runs/ "HTTP/1.1 201 Created"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/flow_runs/4ac697fe-87fa-4c33-89a7-015158e87a10/set_state "HTTP/1.1 201 Created"
2026-04-26 14:16:20 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/flow_runs/4ac697fe-87fa-4c33-89a7-015158e87a10 "HTTP/1.1 200 OK"
2026-04-26 14:16:20 | INFO    | prefect.flow_runs | Beginning flow run 'festive-mink' for flow 'feature-engineering-pipeline'
2026-04-26 14:16:20 | INFO    | prefect.task_runs | Dropping database if it exists...
2026-04-26 14:16:20 | INFO    | src.db_init.db_setup | === SCHEMA SETUP STARTED ===
2026-04-26 14:16:20 | INFO    | src.db_init.db_setup | Database 'retail' dropped.
2026-04-26 14:16:20 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:20 | INFO    | prefect.task_runs | Creating database...
2026-04-26 14:16:21 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/admin/version "HTTP/1.1 200 OK"
2026-04-26 14:16:21 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/flows/1da74eb4-9a28-48f8-96fd-360e923e7375 "HTTP/1.1 200 OK"
2026-04-26 14:16:21 | INFO    | src.db_init.db_setup | Database 'retail' created.
2026-04-26 14:16:21 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:21 | INFO    | prefect.task_runs | Creating schemas and tables...
2026-04-26 14:16:21 | INFO    | src.db_init.db_setup | Running schema.sql...
2026-04-26 14:16:21 | INFO    | src.utils.sql_execute | Executed: D:\projects\customer-rfm-segmentation-dashboard\sql\sql_create\schema.sql
2026-04-26 14:16:21 | INFO    | src.db_init.db_setup | === SCHEMA SETUP COMPLETED SUCCESSFULLY ===
2026-04-26 14:16:21 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:21 | INFO    | prefect.task_runs | Loading base CSV into dim.dim_base_retail...
2026-04-26 14:16:21 | INFO    | src.tasks.load | === LOAD STARTED ===
2026-04-26 14:16:21 | INFO    | src.tasks.load | Loading CSVs into raw...
2026-04-26 14:16:22 | INFO    | httpx | HTTP Request: GET http://127.0.0.1:8508/api/csrf-token?client=38c28c64-79e1-4cfe-b09e-b8e6b8d80bc1 "HTTP/1.1 422 Unprocessable Entity"
2026-04-26 14:16:22 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/logs/ "HTTP/1.1 201 Created"
2026-04-26 14:16:23 | INFO    | src.tasks.load | Loaded raw.raw_base_retail from base_retail.csv
2026-04-26 14:16:23 | INFO    | src.tasks.load | Base loaded.
2026-04-26 14:16:23 | INFO    | src.tasks.load | === LOAD COMPLETED SUCCESSFULLY ===
2026-04-26 14:16:23 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:23 | INFO    | prefect.task_runs | Running dbt models (stg -> int -> dim + mart)...
2026-04-26 14:16:23 | INFO    | src.pipelines.dbt_run | Running: dbt run --project-dir D:\projects\customer-rfm-segmentation-dashboard\dbt --profiles-dir D:\projects\customer-rfm-segmentation-dashboard\dbt --target dev
2026-04-26 14:16:24 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/logs/ "HTTP/1.1 201 Created"
2026-04-26 14:16:33 | INFO    | src.pipelines.dbt_run | 12:16:27  Running with dbt=1.11.8
12:16:27  Registered adapter: postgres=1.10.0
12:16:28  Found 4 models, 10 data tests, 1 source, 466 macros
12:16:28
12:16:28  Concurrency: 4 threads (target='dev')
12:16:28
12:16:29  1 of 4 START sql view model staging.stg_retail ................................. [RUN]
12:16:29  1 of 4 OK created sql view model staging.stg_retail ............................ [CREATE VIEW in 0.22s]
12:16:29  2 of 4 START sql view model intermediate.int_retail_cleaned .................... [RUN]
12:16:29  2 of 4 OK created sql view model intermediate.int_retail_cleaned ............... [CREATE VIEW in 0.06s]
12:16:29  3 of 4 START sql table model dim.dim_customers ................................. [RUN]
12:16:31  3 of 4 OK created sql table model dim.dim_customers ............................ [SELECT 793755 in 2.11s]
12:16:31  4 of 4 START sql view model mart.mart_customer_rfm_features .................... [RUN]
12:16:31  4 of 4 OK created sql view model mart.mart_customer_rfm_features ............... [CREATE VIEW in 0.06s]
12:16:31
12:16:31  Finished running 1 table model, 3 view models in 0 hours 0 minutes and 2.99 seconds (2.99s).
12:16:31
12:16:31  Completed successfully
12:16:31
12:16:31  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4

2026-04-26 14:16:33 | INFO    | src.pipelines.dbt_run | dbt run completed successfully.
2026-04-26 14:16:33 | INFO    | prefect.task_runs | dbt run finished.
2026-04-26 14:16:33 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:33 | INFO    | prefect.task_runs | Running dbt tests...
2026-04-26 14:16:33 | INFO    | src.pipelines.dbt_run | Running: dbt test --project-dir D:\projects\customer-rfm-segmentation-dashboard\dbt --profiles-dir D:\projects\customer-rfm-segmentation-dashboard\dbt --target dev
2026-04-26 14:16:34 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/logs/ "HTTP/1.1 201 Created"
2026-04-26 14:16:40 | INFO    | src.pipelines.dbt_run | 12:16:36  Running with dbt=1.11.8
12:16:36  Registered adapter: postgres=1.10.0
12:16:36  Found 4 models, 10 data tests, 1 source, 466 macros
12:16:36
12:16:36  Concurrency: 4 threads (target='dev')
12:16:36
12:16:37  1 of 10 START test not_null_dim_customers_customer_id .......................... [RUN]
12:16:37  2 of 10 START test not_null_int_retail_cleaned_customer_id ..................... [RUN]
12:16:37  3 of 10 START test not_null_int_retail_cleaned_invoice ......................... [RUN]
12:16:37  4 of 10 START test not_null_int_retail_cleaned_invoice_date .................... [RUN]
12:16:37  3 of 10 PASS not_null_int_retail_cleaned_invoice ............................... [PASS in 0.11s]
12:16:37  5 of 10 START test not_null_mart_customer_rfm_features_customer_id ............. [RUN]
12:16:37  2 of 10 PASS not_null_int_retail_cleaned_customer_id ........................... [PASS in 0.25s]
12:16:37  6 of 10 START test not_null_stg_retail_invoice ................................. [RUN]
12:16:37  4 of 10 PASS not_null_int_retail_cleaned_invoice_date .......................... [PASS in 0.26s]
12:16:37  7 of 10 START test not_null_stg_retail_invoice_date ............................ [RUN]
12:16:37  1 of 10 PASS not_null_dim_customers_customer_id ................................ [PASS in 0.35s]
12:16:37  8 of 10 START test not_null_stg_retail_price ................................... [RUN]
12:16:37  6 of 10 PASS not_null_stg_retail_invoice ....................................... [PASS in 0.11s]
12:16:37  9 of 10 START test not_null_stg_retail_quantity ................................ [RUN]
12:16:37  7 of 10 PASS not_null_stg_retail_invoice_date .................................. [PASS in 0.17s]
12:16:37  10 of 10 START test unique_mart_customer_rfm_features_customer_id .............. [RUN]
12:16:37  8 of 10 PASS not_null_stg_retail_price ......................................... [PASS in 0.29s]
12:16:37  9 of 10 PASS not_null_stg_retail_quantity ...................................... [PASS in 0.28s]
12:16:38  5 of 10 PASS not_null_mart_customer_rfm_features_customer_id ................... [PASS in 1.50s]
12:16:39  10 of 10 PASS unique_mart_customer_rfm_features_customer_id .................... [PASS in 1.38s]
12:16:39
12:16:39  Finished running 10 data tests in 0 hours 0 minutes and 2.18 seconds (2.18s).
12:16:39
12:16:39  Completed successfully
12:16:39
12:16:39  Done. PASS=10 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=10

2026-04-26 14:16:40 | INFO    | src.pipelines.dbt_run | dbt test completed successfully.
2026-04-26 14:16:40 | INFO    | prefect.task_runs | dbt test finished.
2026-04-26 14:16:40 | INFO    | prefect.task_runs | Finished in state Completed()
2026-04-26 14:16:40 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/flow_runs/4ac697fe-87fa-4c33-89a7-015158e87a10/set_state "HTTP/1.1 201 Created"
2026-04-26 14:16:40 | INFO    | prefect.flow_runs | Finished in state Completed()
2026-04-26 14:16:40 | INFO    | httpx | HTTP Request: POST http://127.0.0.1:8508/api/logs/ "HTTP/1.1 201 Created"

df_rfm loaded: 5847 rows, 11 columns

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,r_f_score,segment,return_ratio,avg_order_value
customer_id,,,,,,,,,,
12346,325,14,368.36,2,5,2,25,cant_lose,0.995250,26.311429
12347,1,8,4921.53,5,4,5,54,champions,0.000000,615.191250
12348,74,5,1658.40,3,3,4,33,need_attention,0.000000,331.680000
12349,18,4,3654.54,4,3,5,43,potential_loyalists,0.006565,913.635000
12350,309,1,294.40,2,1,2,21,hibernating,0.000000,294.400000
...,...,...,...,...,...,...,...,...,...,...
18283,3,22,2658.95,5,5,4,55,champions,0.000000,120.861364
18284,431,1,411.68,1,2,2,12,hibernating,0.000000,411.680000
18285,660,1,377.00,1,2,2,12,hibernating,0.000000,377.000000
18286,476,3,1138.43,1,3,3,13,at_risk,0.086647,379.476667
18287,42,8,4127.89,4,4,5,44,loyal_customers,0.001234,515.986250

In [3]:
'''
Pandas feature engineering CAN be used for testing purposes, but not implemented in this project.
The SQL version is the main implementation for feature engineering in this project.
if you have any issues with the SQL feature engineering, I built the pandas version for feature engineering, 
but comment out the SQL version and further testing code to avoid broken logic.
'''
path_base_csv = PROCESSED_DIR / 'base_retail.csv'
df = pd.read_csv(path_base_csv)
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df_pd_featured = pd_feature_engineering(df)
print(f"df_rfm loaded: {df_pd_featured.shape[0]} rows, {df_pd_featured.shape[1]} columns")
df_pd_featured.sort_index(inplace=True)
df_pd_featured

2026-04-26 14:16:43 | INFO    | src.tasks.pd_feature_engineering | === PANDAS FEATURE ENGINEERING STARTED ===
2026-04-26 14:16:44 | INFO    | src.tasks.pd_feature_engineering | === PANDAS FEATURE ENGINEERING COMPLETED SUCCESSFULLY ===

df_rfm loaded: 5847 rows, 10 columns

,recency,frequency,monetary,recency_score,frequency_score,monetary_score,r_f_score,segment,return_ratio,avg_order_value
customer_id,,,,,,,,,,
12346,325,14,368.36,2,5,2,25,cant_lose,0.995250,26.311429
12347,1,8,4921.53,5,4,5,54,champions,0.000000,615.191250
12348,74,5,1658.40,3,3,4,33,need_attention,0.000000,331.680000
12349,18,4,3654.54,4,3,5,43,potential_loyalists,0.006565,913.635000
12350,309,1,294.40,2,1,2,21,hibernating,0.000000,294.400000
...,...,...,...,...,...,...,...,...,...,...
18283,3,22,2658.95,5,5,4,55,champions,0.000000,120.861364
18284,431,1,411.68,1,2,2,12,hibernating,0.000000,411.680000
18285,660,1,377.00,1,2,2,12,hibernating,0.000000,377.000000
18286,476,3,1138.43,1,3,3,13,at_risk,0.086647,379.476667
18287,42,8,4127.89,4,4,5,44,loyal_customers,0.001234,515.986250

In [4]:
df_overview(df_sql_featured)

================================= Shape =================================
(5847, 10)
================================= Info =================================
<class 'pandas.core.frame.DataFrame'>
Index: 5847 entries, 12346 to 18287
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   recency          5847 non-null   int64
 1   frequency        5847 non-null   int64
 2   monetary         5847 non-null   float64
 3   recency_score    5847 non-null   int64
 4   frequency_score  5847 non-null   int64
 5   monetary_score   5847 non-null   int64
 6   r_f_score        5847 non-null   object
 7   segment          5847 non-null   object
 8   return_ratio     5847 non-null   float64
 9   avg_order_value  5847 non-null   float64
dtypes: float64(3), int64(5), object(2)
memory usage: 502.5+ KB
None
================================= Columns =================================
Index(['recency', 'frequency', 'monetary', 'recency_score', 'frequency_score',
       'monetary_score', 'r_f_score', 'segment', 'return_ratio',
       'avg_order_value'],
      dtype='object')
================================= Describe =================================
           recency    frequency       monetary  recency_score  \
count  5847.000000  5847.000000    5847.000000    5847.000000
mean    196.689071     7.499230    2797.871047       3.000513
std     207.753953    15.403045   13830.331759       1.414395
min       0.000000     1.000000       0.000000       1.000000
25%      23.000000     2.000000     331.565000       2.000000
50%      91.000000     4.000000     841.200000       3.000000
75%     375.000000     8.000000    2172.420000       4.000000
max     738.000000   466.000000  578408.640000       5.000000

       frequency_score  monetary_score  return_ratio  avg_order_value
count      5847.000000     5847.000000   5847.000000      5847.000000
mean          2.999487        2.999487      0.022750       308.850164
std           1.414395        1.414395      0.081171       409.338436
min           1.000000        1.000000      0.000000         0.000000
25%           2.000000        2.000000      0.000000       151.604375
50%           3.000000        3.000000      0.000000       229.738000
75%           4.000000        4.000000      0.014676       355.392500
max           5.000000        5.000000      1.000000     11880.840000
================================= NaN =================================
recency            0
frequency          0
monetary           0
recency_score      0
frequency_score    0
monetary_score     0
r_f_score          0
segment            0
return_ratio       0
avg_order_value    0
dtype: int64
================================= Duplicates =================================
1
================================= Cardinality & Top Values =================================
r_f_score 25 r_f_score
55    0.097315
11    0.089619
12    0.062083
45    0.054729
34    0.054558
Name: proportion, dtype: float64
segment 10 segment
hibernating            0.255516
loyal_customers        0.193775
champions              0.140927
at_risk                0.128784
potential_loyalists    0.123824
Name: proportion, dtype: float64

- 5847 customers for the analysis and modeling;
- no NaNs;
- correct dtypes;
- right features;
- no unexpected values for rfm calc;

In [5]:
df_overview(df_pd_featured)

================================= Shape =================================
(5847, 10)
================================= Info =================================
<class 'pandas.core.frame.DataFrame'>
Index: 5847 entries, 12346 to 18287
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   recency          5847 non-null   int64
 1   frequency        5847 non-null   int64
 2   monetary         5847 non-null   float64
 3   recency_score    5847 non-null   int64
 4   frequency_score  5847 non-null   int64
 5   monetary_score   5847 non-null   int64
 6   r_f_score        5847 non-null   object
 7   segment          5847 non-null   object
 8   return_ratio     5847 non-null   float64
 9   avg_order_value  5847 non-null   float64
dtypes: float64(3), int64(5), object(2)
memory usage: 502.5+ KB
None
================================= Columns =================================
Index(['recency', 'frequency', 'monetary', 'recency_score', 'frequency_score',
       'monetary_score', 'r_f_score', 'segment', 'return_ratio',
       'avg_order_value'],
      dtype='object')
================================= Describe =================================
           recency    frequency      monetary  recency_score  frequency_score  \
count  5847.000000  5847.000000  5.847000e+03    5847.000000      5847.000000
mean    196.689071     7.499230  2.797871e+03       3.000000         3.000000
std     207.753953    15.403045  1.383033e+04       1.414576         1.414576
min       0.000000     1.000000 -2.664535e-15       1.000000         1.000000
25%      23.000000     2.000000  3.315650e+02       2.000000         2.000000
50%      91.000000     4.000000  8.412000e+02       3.000000         3.000000
75%     375.000000     8.000000  2.172420e+03       4.000000         4.000000
max     738.000000   466.000000  5.784086e+05       5.000000         5.000000

       monetary_score  return_ratio  avg_order_value
count     5847.000000   5847.000000     5.847000e+03
mean         3.000000      0.022750     3.088502e+02
std          1.414576      0.081171     4.093384e+02
min          1.000000      0.000000    -1.332268e-15
25%          2.000000      0.000000     1.516044e+02
50%          3.000000      0.000000     2.297380e+02
75%          4.000000      0.014676     3.553925e+02
max          5.000000      1.000000     1.188084e+04
================================= NaN =================================
recency            0
frequency          0
monetary           0
recency_score      0
frequency_score    0
monetary_score     0
r_f_score          0
segment            0
return_ratio       0
avg_order_value    0
dtype: int64
================================= Duplicates =================================
1
================================= Cardinality & Top Values =================================
r_f_score 25 r_f_score
55    0.097315
11    0.089619
12    0.062083
45    0.054900
34    0.054729
Name: proportion, dtype: float64
segment 10 segment
hibernating            0.255687
loyal_customers        0.193775
champions              0.140927
at_risk                0.128784
potential_loyalists    0.123824
Name: proportion, dtype: float64

- some columns values are visually shown in exponent;
- r_f_score distribution is identical;
- segment destribution differs slightly;

In [6]:
# Testing dataframes on equality
# pd.testing.assert_frame_equal(df_pd_featured, df_sql_featured, check_dtype=False)

- mismatch is small, less than 0.1% (0.05131%), the calculated data is almost identical;
- as I found, pandas qcut and rank have slighly different logic than NTILE in SQL, it probably causes this behavior;
- it is a better approach to do a full test to find out the exact causes, but the pandas version is here not primarily for testing purposes;

In [7]:
pd_to_csv_path = os.path.join('..', 'data', '03_featured', 'featured_retail.csv')

os.makedirs(os.path.dirname(pd_to_csv_path), exist_ok=True)
df_sql_featured.to_csv(pd_to_csv_path)

print(f"Saved to: {pd_to_csv_path}")

Saved to: ..\data\03_featured\featured_retail.csv

- the SQL version is used as canonical and saved as featured csv;

## Summary of RFM Feature Engineering

### Approach:
- RFM metrics calculated using both **SQL (canonical)** and **Pandas (additional)**
- Return ratio and average order value are calculated for better segmentation and analysis to support RFM scores.

### Key Outputs:
- **5,847 customers** retained after cleaning, with no missing values and correct dtypes
- SQL and Pandas implementations produce near-identical results (**< 0.1% mismatch**, ~0.051%)
- Minor differences may be due to logic difference between NTILE and Pandas `qcut`

### Next Steps:
The featured dataset has been saved to `../data/03_featured/featured_rfm_retail.csv` and is ready for:
1. Post-feature EDA (RFM distributions, segment profiling, correlation analysis)
2. Customer segmentation modeling (clustering)